### ISSUE TITLE
Test failure in IfritTests.Fuse_TestsTokenize/testProtocolWeightedSearchTokenized

### ISSUE THREAD

**Issue by dfabulich** [ukushu/Ifrit#11]
```
% swift test --filter IfritTests.Fuse_TestsTokenize/testProtocolWeightedSearchTokenized
```

```
/Users/dfabulich/git/Ifrit/Tests/Ifrit_FuseTests/Fuse_TestsTokenize.swift:74: error: -[IfritTests.Fuse_TestsTokenize testProtocolWeightedSearchTokenized] : XCTAssertTrue failed - The first result is the first book
/Users/dfabulich/git/Ifrit/Tests/Ifrit_FuseTests/Fuse_TestsTokenize.swift:75: error: -[IfritTests.Fuse_TestsTokenize testProtocolWeightedSearchTokenized] : XCTAssertTrue failed - The second result is the second book
```

I ran `git bisect` and found that it started failing in 6cde912baae9ad871b2173bc01e6e9479212c9ec
