### PR TITLE
Revert default `objSortStrategy` to `.averageScore`

### LINKED ISSUE #11: Test failure in IfritTests.Fuse_TestsTokenize/testProtocolWeightedSearchTokenized
```
% swift test --filter IfritTests.Fuse_TestsTokenize/testProtocolWeightedSearchTokenized
```

```
/Users/dfabulich/git/Ifrit/Tests/Ifrit_FuseTests/Fuse_TestsTokenize.swift:74: error: -[IfritTests.Fuse_TestsTokenize testProtocolWeightedSearchTokenized] : XCTAssertTrue failed - The first result is the first book
/Users/dfabulich/git/Ifrit/Tests/Ifrit_FuseTests/Fuse_TestsTokenize.swift:75: error: -[IfritTests.Fuse_TestsTokenize testProtocolWeightedSearchTokenized] : XCTAssertTrue failed - The second result is the second book
```

I ran `git bisect` and found that it started failing in 6cde912baae9ad871b2173bc01e6e9479212c9ec

### PR DESCRIPTION
**Pull request by dfabulich**
In 6cde912 `objSortStrategy` was introduced, allowing users to choose whether to sort by average score or minimal score. Prior to that commit, Ifrit would always sort objects by their average score.

But the commit also changed the default `objSortStrategy` to `.minimalScore`, breaking backwards compatibility and breaking one of the automated tests.

This commit sets the default strategy to `.averageScore`, as it used to be, and fixes the automated test.

Fixes #11

### CODE REVIEW

**Comment by ukushu** [comment]
I believe it's better to fix the tests, as `.minimalScore` reflects a more intuitive behavior than `.averageScore`.

Could you please update tests to use `.minimalScore` logic?

And thanks for your PR

**Comment by dfabulich** [comment]
I can do that, but if we do that, I recommend:

1. Releasing Ifrit 2.0.6 merging this PR to revert the change, unbreaking backwards compatibility
2. Releasing Ifrit 3.0.0 announcing the breaking change in the default, and clarifying that it's backwards incompatible
